[+]================================================[+]
[+]=> [ !ggbb ] = Testa Geradas do Banco do brasil [+]
[+]                                                [+]
[+]=> ex : !ggbb 5522896325412354|10|2021|000      [+]
[+]                                                [+]
[+]=> [ !chk ] = Testa Cartões FULL                [+]
[+]                                                [+]
[+]=> ex : !chk 5088903021236580|10|2021|350       [+]
[+]                                                [+]
[+]=> [ !cpf - !cns - !nome ] Consulta de Dados    [+]
[+]                                                [+]
[+]=> ex : !nome + sobrenome - !cpf + 11 digitos   [+]
[+]                                                [+]
[+]=> [ !lookup ] Pesquisa um certo IP             [+]
[+]                                                [+]
[+]=> ex: !lookup 8.8.8.8                          [+]
[+]                                                [+]
[+]=> [ !sro ] Rastreia um codigo do Correios      [+]
[+]                                                [+]
[+]=> ex : !sro  PT113178279BR                     [+]
[+]                                                [+]
[+]=> [ !dados ] gera dados falsos - Fake data BR  [+]
[+]                                                [+]
[+]=> [ !tempmail ] gera email temporario          [+]
[+]                                                [+]
[+]=> [ !bin ] pesquisa bin de um cartão           [+]
[+]                                                [+]
[+]=> [ !proxy ] o Bot Lhe Fornecerá um ip Proxy   [+]
[+]                                                [+]
[+]=> [ !cell] Procura por Um Numero de telefone   [+]
[+]                                                [+]
[+]=> ex: !cell 55999214256                        [+]
[+]                                                [+]
[+]=> [ !netflix ] Checa uma Conta Netflix         [+]
[+]                                                [+]
[+]=> ex !netflix chknet@chknet.com:teste123       [+]
[+]                                                [+]
[+]=> [ !pagseguro ] Checa uma Conta Pagseguro     [+]
[+]                                                [+]
[+]=> ex !pagseguro chknet@chknet.com:teste123     [+]
[+]                                                [+]
[+]=> [ !vendas ] Mostra Vendedores Verificados    [+]
[+]                                                [+]
[+]================================================[+]
[+]   MEMBROS DA STAFF - #CARDER - irc.chknet.cc   [+]
[+]================================================[+]
[+] {NORAH_C_IV} = FOUNDER SIGLA: ~                [+]
[+] {J4CKASS}  = OPERATOR SIGLA: @                 [+]
[+] {CHECKNET} = HALF-OP (BOT) SIGLA: %            [+]
[+] {GENEILTON01} = OPERATOR SIGLA: @              [+]
[+] {PAYMENT} = HALF-OP SIGLA: %                   [+]
[+] {SIGINT} = HALF-OP SIGLA: %                    [+]
[+]================================================[+]
[+]           END RAW FILE <~Norah_C_IV>           [+]
[+]================================================[+]